---
- name: Converge kubernetes control plane
  hosts: all
  become: true
  pre_tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
  roles:
    - role: kubernetes
  vars:
    vendor: containerd

