---
- name: Verify kubernetes
  hosts: all
  tasks: 
    - name: Get kubelet binary path
      shell: which kubelet
      register: kubelet_bin_path

    - name: Ensure the kubelet binary path installed
      assert:
        that:
          - "kubelet_bin_path.stdout != ''"

    - name: Get kubeadm binary path
      shell: which kubeadm
      register: kubeadm_bin_path

    - name: Ensure the kubeadm binary path installed
      assert:
        that:
          - "kubeadm_bin_path.stdout != ''"

    - name: Get kubectl binary path
      shell: which kubectl
      register: kubectl_bin_path

    - name: Ensure the kubectl binary path installed
      assert:
        that:
          - "kubectl_bin_path.stdout != ''"
