---
- name: Create kubernetes-cri.conf
  shell: |
    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF
  become: yes

- name: Apply sysctl params without reboot
  shell: |
    sysctl --system
  become: yes

- include_tasks: containerd.yaml
  when: vendor == "containerd"

- include_tasks: runc.yaml

- include_tasks: cni_plugins.yaml

- include_tasks: crictl.yaml
