---
- name: Download kubelet
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubelet_version }}/bin/linux/{{ arch }}/kubelet
    dest: /usr/local/bin
    mode: +x
  become: yes

- name: Download kubelet systemd
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service
    dest: /etc/systemd/system/kubelet.service
  become: yes

- name: Replace kubelet binary path on kubelet.service
  replace:
    path: /etc/systemd/system/kubelet.service
    regexp: "\/usr\/bin"
    replace: "/usr/local/bin"
  become: yes

- name: Create kubelet.service.d directory
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    recurse: yes
  become: yes

- name: Download kubelet kubeadm config
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: yes

- name: Replace kubelet binary path on kubelet.service
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: "\/usr\/bin"
    replace: "/usr/local/bin"
  become: yes

- name: Enable kubelet systemd
  systemd:
    state: started
    name: kubelet
    enabled: yes
    daemon_reload: yes
  become: yes
