---
- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - socat
    - conntrack
  become: yes

- name: Hold required dependencies version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - socat
    - conntrack
  become: yes

- name: Create kubernetes folder
  file:
    path: /opt/kubernetes
    state: directory
  become: yes

- include_tasks: kubelet.yaml
- include_tasks: kubectl.yaml
- include_tasks: kubeadm.yaml

- tags: notest
  include_tasks: swap.yaml

- tags: notest
  include_tasks: init-control-plane.yaml
  when: kubeadm_action == "init_control_plane"
